[[history]]
== 历史与致谢

=== “为什么要开发新的 ISA？” 伯克利团队的理由

我们开发 RISC-V 以支持我们在研究和教育中的需求，我们的团队特别对研究理念的实际硬件实现感兴趣（自本规范第一版以来，我们已经完成了十一种不同硅片的 RISC-V 实现），并为学生们在课堂中探讨提供真实的实现（RISC-V 处理器 RTL 设计已在伯克利的多门本科和研究生课程中使用）。 在我们当前的研究中，我们尤其对专用和异构加速器的转变感兴趣，这种转变是由传统晶体管缩放结束所引发的功率限制推动的。 我们希望有一个高度灵活和可扩展的基础 ISA，以此为基础来建立我们的研究工作。

我们被反复问到的问题是“为什么开发新的 ISA？”
使用现有商业 ISA 的最明显的好处是其大型且广泛支持的软件生态系统，包括开发工具和移植的应用，可以在研究和教学中加以利用。 其他好处包括存在大量文档和教程示例。 然而，我们在研究和教学中使用商业指令集的经验表明，这些好处在实际中较小，且不利于这些缺点：

* *商业 ISA 是专有的。* 除了 SPARC V8 是一个开放的 IEEE 标准 cite:[sparcieee1994] ，大多数商业 ISA 的所有者都小心地保护其知识产权，并不欢迎自由公开的竞争性实现。 对于仅使用软件模拟器的学术研究和教学来说，这是一个小的问题，但对于那些希望分享实际 RTL 实现的团队来说，这是一个主要担忧。 对于那些不愿信任少数商业 ISA 实现来源，但却被禁止创建自己的洁净室实现的实体来说，这也是一个主要担忧。 我们不能保证所有 RISC-V 实现都不会侵犯第三方专利，但我们可以保证我们不会尝试起诉 RISC-V 实现者。
* *商业 ISA 仅在某些市场领域流行。* 在撰写本文时，最明显的例子是 ARM 架构在服务器领域的支持不佳，而 Intel x86 架构（或几乎所有其他架构）在移动领域的支持不佳，尽管 Intel 和 ARM 都在尝试进入对方的市场领域。 另一个例子是 ARC 和 Tensilica，它们提供可扩展的核心，但专注于嵌入领域。
这种市场细分稀释了支持特定商用 ISA 的好处，因为在实践中软件生态系统仅存在于某些领域，并必须为其他领域构建。
* *商业 ISA 兴衰不定。* 以前的研究基础设施已经围绕不再流行（如 SPARC、MIPS）甚至不再生产的（如 Alpha）商业 ISA 建立。 这些丧失了活跃的软件生态系统的好处，而 ISA 和支持工具的挥之不去的知识产权问题妨碍了感兴趣的第三方继续支持 ISA 的能力。 一个开放的 ISA 可能也会失去流行性，但任何感兴趣的一方都可以继续使用和发展这一生态系统。
* *流行的商业 ISA 十分复杂。* 主流商业 ISA（x86 和 ARM）在硬件中实现到支持常见的软件栈和操作系统的水平非常复杂。 更糟糕的是，几乎所有的复杂性都是由于错误的，或者至少是过时的 ISA 设计决策，而不是那些真正提高效率的特性。
* *仅靠商业 ISA 不足以启动应用程序。* 即使我们费力地实现了一个商业 ISA，这也不足以运行该 ISA 的现有应用程序。 大多数应用程序需要完整的 ABI（应用程序二进制接口），而不仅仅是用户级 ISA。 大多数 ABI 依赖于库，这些库又依赖于操作系统的支持。 运行现有操作系统需要实现操作系统期望的主管级 ISA 和设备接口。 这些通常比用户级 ISA 规范较少，并且更为复杂。
* *流行的商业 ISA 并未为可扩展性设计。* 主流商业 ISA 并未特别为可扩展性设计，结果是随着指令集的增长增加了相当多的指令编码复杂性。 公司如 Tensilica（被 Cadence 收购）和 ARC（被 Synopsys 收购）已经围绕可扩展性构建了 ISA 和工具链，但他们专注于嵌入式应用，而不是通用计算系统。
* *一个修改过的商业 ISA 就是一个新的 ISA。* 我们的主要目标之一是支持架构研究，包括重大 ISA 扩展。 即使是小的扩展也减少了使用标准 ISA 的好处，因为编译器必须修改，应用程序必须从源代码重新构建以使用扩展。 引入新架构状态的较大扩展还需要对操作系统进行修改。 最终，修改过的商业 ISA 变成了一个新的 ISA，但带来了基础 ISA 的所有旧负担。

我们的立场是，ISA 或许是计算系统中最重要的接口，而没有理由让这样一个重要的接口成为专有。 主流商业 ISA 是基于30多年前已经非常成熟的指令集概念的。 软件开发人员应该能够针对开放标准的硬件目标，而商业处理器设计者应该在实现质量上进行竞争。

我们不是第一个探讨适用于硬件实现的开放 ISA 设计的人。 我们还考虑了其他现有的开放 ISA 设计，其中最接近我们目标的是 OpenRISC 架构 cite:[openriscarch]。 由于几个技术原因，我们决定不采用 OpenRISC ISA：

* OpenRISC 具有条件码和分支延迟槽，这使得高性能的实现变得复杂。
* OpenRISC 使用固定的 32 位编码和 16 位立即数，这排除了更密集的指令编码，并限制了 ISA 后续扩展的空间。
* OpenRISC 不支持 IEEE 754 浮点标准的 2008 年修订。
* 当我们开始时，OpenRISC 64 位设计尚未完成。

从头开始设计得以使我们设计一个满足我们所有目标的 ISA，尽管这当然比我们最初计划的要耗费更多的精力。 我们已投入相当大的努力建立 RISC-V ISA 基础设施，包括文档、编译器工具链、操作系统端口、参考 ISA 模拟器、FPGA 实现、高效的 ASIC 实现、架构测试套件以及教学材料。 自本手册上一版以来，RISC-V ISA 已在学术界和工业界大量采用，我们已经创建了非营利性 RISC-V 基金会来保护和促进该标准。 RISC-V 基金会网站 https://riscv.org 包含有关基金会会员及使用 RISC-V 的各种开源项目的最新信息。

=== ISA 手册 1.0 版的历史

RISC-V ISA 和指令集手册建立在几个早期项目的基础上。 主管级机器的几个方面和手册的总体格式可追溯到 1992 年在 UC Berkeley 和 ICSI 开始的 T0（Torrent-0）矢量微处理器项目。 T0 是一个基于 MIPS-II ISA 的矢量处理器，由 Krste Asanović 担任主要架构师和 RTL 设计师，Brian Kingsbury 和 Bertrand Irrisou 担任主要 VLSI 实现者。 ICSI 的 David Johnson 是 T0 ISA 设计的重要贡献者，特别是主管模式，以及手册文本的撰写。 John Hauser 还对 T0 ISA 设计提供了大量反馈。

麻省理工学院的 Scale（Software-Controlled Architecture for Low Energy）项目始于 2000 年，基于 T0 项目基础设施构建，优化了主管级接口，并通过去掉分支延迟槽从 MIPS 标量 ISA 中脱离。 Ronny Krashinsky 和 Christopher Batten 是 MIT 的 Scale 矢量线程处理器的主要架构师，而 Mark Hampton 负责为 Scale 移植基于 GCC 的编译器基础设施和工具。

较为简化的 T0 MIPS 标量处理器规范（MIPS-6371）版本被用于教学新的版本的 MIT 6.371 VLSI 系统导论课程，该课程在 2002 年秋季学期，由 Chris Terman 和 Krste Asanović 授课。 Chris Terman 为课堂提供了大部分实验材料（没有助教！）。 6.371 课程发展为 MIT 的 6.884 复杂数字设计试验课，该课在 2005 年春季由 Arvind 和 Krste Asanović 授课，并成为常规的春季课程 6.375。 一个基于 MIPS 的标量 ISA 的简化版本，名为 SMIPS，被用于 6.884/6.375 课程。 Christopher Batten 是这些课程的早期助教，并围绕 SMIPS ISA 开发了大量文档和实验材料。
这些相同的 SMIPS 实验材料由助教 Yunsup Lee 适应并增强，用于 UC Berkeley 的 2009 年秋季 CS250 VLSI 系统设计课程，该课程由 John Wawrzynek、Krste Asanović 和 John Lazzaro 授课。

Maven（Malleable Array of Vector-thread ENgines）项目是一个第二代矢量线程架构。 Christopher Batten 是 Maverick 设计的主导者，当时他是从 2007 年夏天开始在 UC Berkeley 的交换学者。 来自日立的访问行业研究员 Hidetaka Aoki 对早期 Maven ISA 和微架构设计提出了大量反馈。 Maven 的基础设施基于 Scale 的基础设施，但 Maven ISA 更进一步地偏离了在 Scale 中定义的 MIPS ISA 变体，采用了统一的浮点和整数寄存器文件。 Maven 设计用于支持替代数据并行加速器的实验。 Yunsup Lee 是各种 Maven 矢量单元的主要实现者，而 Rimas Avižienis 则是各种 Maven 标量单元的主要实现者。 Yunsup Lee 和 Christopher Batten 将 GCC 移植以配合新的 Maven ISA。
Christopher Celio 提供了 Maven 的传统矢量指令集（“Flood”）变体的初始定义。

基于与所有这些先前项目的经验，RISC-V ISA 的定义始于 2010 年夏天，由 Andrew Waterman、Yunsup Lee、Krste Asanović 和 David Patterson 作为主要设计者。 RISC-V 32 位指令子集的一个最初版本在 UC Berkeley 的 2010 年秋季 CS250 VLSI 系统设计课程中使用，Yunsup Lee 担任助教。 RISC-V 是对先前 MIPS 启发设计的重新定义。 John Hauser 对浮点 ISA 定义做出了贡献，包括符号注入指令和允许浮点值内部重新编码的寄存器编码方案。

=== ISA 手册 2.0 版的历史

多种 RISC-V 处理器的实现已完成，包括多个硅片制造，如 <<silicon, Fabricated RISC-V testchips table>> 中所示。

[[silicon]]
[%autowidth, float="center", align="center", cols="^,^,^,^", options="header"]
|===
|名称 |流片日期 |工艺 |ISA

|Raven-1 |2011年5月29日 |ST 28nm FDSOI |RV64G1_Xhwacha1

|EOS14 |2012年4月1日 |IBM 45nm SOI |RV64G1p1_Xhwacha2

|EOS16 |2012年8月17日 |IBM 45nm SOI |RV64G1p1_Xhwacha2

|Raven-2 |2012年8月22日 |ST 28nm FDSOI |RV64G1p1_Xhwacha2

|EOS18 |2013年2月6日 |IBM 45nm SOI |RV64G1p1_Xhwacha2

|EOS20 |2013年7月3日 |IBM 45nm SOI |RV64G1p99_Xhwacha2

|Raven-3 |2013年9月26日 |ST 28nm SOI |RV64G1p99_Xhwacha2

|EOS22 |2014年3月7日 |IBM 45nm SOI |RV64G1p9999_Xhwacha3
|===

第一批 RISC-V 处理器在 Verilog 中编写，并由 ST 在 FDSOI 技术预生产中制造，作为 2011 年 Raven-1 测试芯片。 由 Yunsup Lee 和 Andrew Waterman 开发了两个核心，在 Krste Asanović 的指导下，共同行使其职能并进行制造：1）具有错误检测触发器的 RV64 标量核心，2）具有附加 64 位浮点矢量单元的 RV64 核心。 第一个微架构非正式地被称为"TrainWreck"，由于可用于完成设计的时间短且设计库尚不成熟。

随后，由 Andrew Waterman、Rimas Avižienis 和 Yunsup Lee，获得 Krste Asanović 的指导，开发了一种清晰的微架构，用以解耦的 RV64 核心，并继承了铁路主题，被命名为"Rocket"，以纪念乔治·史蒂芬森成功的蒸汽机车设计。 Rocket 是用 Chisel 编写的，这是一种在 UC Berkeley 开发的新硬件设计语言。 在 Rocket 中使用的 IEEE 浮点单元由 John Hauser、Andrew Waterman 和 Brian Richards 开发。 Rocket 之后被进一步改进和开发，并在 FDSOI（Raven-2，Raven-3）中再次制造两次，并在 IBM SOI 技术下（EOS14、EOS16、EOS18、EOS20、EOS22）为一个光子学项目制造五次。 正在进行工作以使 Rocket 设计可作为参数化 RISC-V 处理器生成器使用。

EOS14-EOS22 芯片包括 Hwacha 的早期版本，一个 64 位 IEEE 浮点矢量单元，由 Yunsup Lee、Andrew Waterman、Huy Vo、Albert Ou、Quan Nguyen 和 Stephen Twigg 开发，在 Krste Asanović 指导下。 EOS16-EOS22 芯片包括由 Henry Cook 和 Andrew Waterman 开发的具有缓存一致性协议的双核，由 Krste Asanović 指导。 EOS14 硅运行成功达到了 1.25 GHz。 EOS16 硅因 IBM 封装库的 bug 而受挫。 EOS18 和 EOS20 已成功运行达到了 1.35 GHz。

Raven 测试芯片的贡献者包括 Yunsup Lee、Andrew Waterman、Rimas Avižienis、Brian Zimmer、Jaehwa Kwak、Ruzica Jevtić、Milovan Blagojević、Alberto Puggelli、Steven Bailey、Ben Keller、Pi-Feng Chiu、Brian Richards、Borivoje Nikolić 和 Krste Asanović。

EOS 测试芯片的贡献者包括 Yunsup Lee、Rimas Avižienis、Andrew Waterman、Henry Cook、Huy Vo、Daiwei Li、Chen Sun、Albert Ou、Quan Nguyen、Stephen Twigg、Vladimir Stojanović 和 Krste Asanović。

Andrew Waterman 和 Yunsup Lee 开发了 C++ ISA 模拟器 "Spike"，它被用作开发中的金模，名字来源于庆祝美国跨大陆铁路竣工时使用的金色道钉。 Spike 已作为 BSD 开源项目提供。

Andrew Waterman 完成了一篇有关 RISC-V 压缩指令集的初步设计的硕士论文 cite:[waterman-ms]。

已经完成了各种 RISC-V 的 FPGA 实现，主要作为 Par Lab 项目研究研讨会的集成演示的一部分。 最大规模的 FPGA 设计有 3 个缓存一致的 RV64IMA 处理器，运行研究操作系统。 FPGA 实现的贡献者包括 Andrew Waterman、Yunsup Lee、Rimas Avižienis 和 Krste Asanović。

RISC-V 处理器已在 UC Berkeley 的多个课程中使用。
Rocket 被用作 2011 年秋季 CS250 课程中基于的项目，由 Brian Zimmer 担任助教。 在 2012 年春季本科 CS152 课程中，Christopher Celio 使用 Chisel 编写了一套名为 "Sodor" 的教学 RV32 处理器，命名取自 "托马斯和他的朋友们" 所居住的岛屿 Sodor。 该套件包括一个微代码核心、一个未流水化核心，以及 2、3 和 5 级的流水线核心，并且已根据 BSD 许可证公开可用。 该套件随后更新，并在 2013 年春季由 Yunsup Lee 担任助教的 CS152 课程和 2014 年春季由 Eric Love 担任助教的 CS152 课程中再次使用。 Christopher Celio 还开发了一个称为 BOOM（Berkeley Out-of-Order Machine）的乱序 RV64 设计，附有流水线可视化，用于 CS152 课程中。 CS152 课程还使用了 Andrew Waterman 和 Henry Cook 开发的缓存一致版本的 Rocket 核心。

2013 年夏天，定义了 RoCC（Rocket Custom Coprocessor）接口，以简化向 Rocket 核心添加定制加速器。
Rocket 和 RoCC 接口在 2013 年秋季由 Jonathan Bachrach 授课的 CS250 VLSI 课程中被广泛使用，开发了多个基于 RoCC 接口的学生加速器项目。 Hwacha 矢量单元被改写为 RoCC 协处理器。

两位伯克利大学本科生 Quan Nguyen 和 Albert Ou 已于 2013 年春天成功将 Linux 移植至 RISC-V 上。

Colin Schmidt 在 2014 年 1 月成功完成了 RISC-V 2.0 的 LLVM 后端。

Darius Rad 在 Bluespec 向 GCC 移植中贡献了软浮点 ABI 支持，于 2014 年 3 月。

John Hauser 贡献了浮点分类指令的定义。

我们知道有多个其他 RISC-V 核心实现，包括 Tommy Thorn 在 Verilog 中的一个，并且 Rishiyur Nikhil 在 Bluespec 中的一个。

=== 致谢

感谢 Christopher F. Batten、Preston Briggs、Christopher Celio、David Chisnall、Stefan Freudenberger、John Hauser、Ben Keller、Rishiyur Nikhil、Michael Taylor、Tommy Thorn 和 Robert Watson 对 ISA 2.0 版草稿提出的意见。

=== 历史来自版本 2.1

自冻结版本 2.0 于 2014 年 5 月引入以来，RISC-V ISA 的接受速度非常快，在这样一个简短的历史部分中难以记录如此多的活动。 或许最重要的单一事件是在 2015 年 8 月成立的非营利性 RISC-V 基金会。 基金会将接管 RISC-V ISA 标准的管理，而官方网页 `riscv.org` 是获取 RISC-V 标准新闻和更新的最佳地方。

=== 致谢

感谢 Scott Beamer、Allen J. Baum、Christopher Celio、David Chisnall、Paul Clayton、Palmer Dabbelt、Jan Gray、Michael Hamburg 和 John Hauser 对 2.0 版规范的意见。

=== 历史来自版本 2.2

=== 致谢

感谢 Jacob Bachmeyer、Alex Bradbury、David Horner、Stefan O'Rear 和 Joseph Myers 对 2.1 版规范的意见。

=== 2.3 版的历史

RISC-V 的接纳度继续以非常快的速度推进。

John Hauser 和 Andrew Waterman 在 Paolo Bonzini 提案的基础上贡献了一个虚拟机管理程序 ISA 扩展。

Daniel Lustig、Arvind、Krste Asanović、Shaked Flur、Paul Loewenstein、Yatin Manerkar、Luc Maranget、Margaret Martonosi、Vijayanand Nagarajan、Rishiyur Nikhil、Jonas Oberhauser、Christopher Pulte、Jose Renau、Peter Sewell、Susmit Sarkar、Caroline Trippel、Muralidaran Vijayaraghavan、Andrew Waterman、Derek Williams、Andrew Wright 和 Sizhuo Zhang 然然 名此模型的贡献者。

=== 资助

RISC-V 架构和实现的开发部分由以下赞助商资助。

* *Par Lab:* 研究由 Microsoft（奖项 # 024263）和 Intel（奖项 # 024894）资助，并由 UC 配套资金资助。 Discovery（奖项 # DIG07-10227）。 额外的支持来自 Par Lab 附属公司诺基亚、英伟达、甲骨文和三星。
* *Project Isis:* 美国能源部奖项 DE-SC0003624。
* *ASPIRE Lab*: DARPA PERFECT 计划，奖项 HR0011-12-2-0016。 DARPA POEM 计划奖项 HR0011-11-C-0100。 未来架构研究中心 (C-FAR)，这一由半导体研究公司资助的 STARnet 中心。 来自 ASPIRE 工业赞助商英特尔和 ASPIRE 附属企业 Google、惠普企业、华为、诺基亚、英伟达、甲骨文和三星的额外支持。

本文内容不一定反映美国政府的立场或政策，不应推断为官方认可。